using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using LuminaDesktop.Modules.LumaEdges; // For HotkeySender

namespace LuminaDesktop.Modules
{
    public class MouseGestureModule : IDisposable
    {
        private bool _isRunning;

        // Mouse Hook Constants
        private const int WH_MOUSE_LL = 14;
        private const int WM_MOUSEMOVE = 0x0200;
        private const int WM_RBUTTONDOWN = 0x0204;
        private const int WM_RBUTTONUP = 0x0205;

        private const uint GESTURE_MAGIC_EXTRA_INFO = 0x12345678;
        private const int GESTURE_MIN_DISTANCE = 15;

        private delegate nint LowLevelMouseProc(int nCode, nint wParam, nint lParam);
        private LowLevelMouseProc? _mouseProcDelegate;
        private nint _mouseHookId = nint.Zero;

        // Gesture state
        private bool _isRightDown = false;
        private readonly List<System.Drawing.Point> _path = new();

        public void Start()
        {
            if (_isRunning) return;
            _isRunning = true;

            _mouseProcDelegate = MouseHookCallback;
            using (var curProcess = Process.GetCurrentProcess())
            using (var curModule = curProcess.MainModule)
            {
                if (curModule != null)
                    _mouseHookId = SetWindowsHookEx(WH_MOUSE_LL, _mouseProcDelegate, GetModuleHandle(curModule.ModuleName), 0);
            }
        }

        public void Stop()
        {
            if (!_isRunning) return;
            _isRunning = false;

            if (_mouseHookId != nint.Zero)
            {
                UnhookWindowsHookEx(_mouseHookId);
                _mouseHookId = nint.Zero;
            }
        }

        private nint MouseHookCallback(int nCode, nint wParam, nint lParam)
        {
            if (nCode >= 0)
            {
                var hookStruct = Marshal.PtrToStructure<MSLLHOOKSTRUCT>(lParam);

                // Ignore synthetic events generated by us
                if (hookStruct.dwExtraInfo == (nint)GESTURE_MAGIC_EXTRA_INFO)
                {
                    return CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
                }

                var msg = (int)wParam;

                if (msg == WM_RBUTTONDOWN)
                {
                    string processName = GetForegroundProcessName();
                    if (!string.IsNullOrEmpty(processName))
                    {
                        var settings = SettingsService.Load();
                        bool isTarget = false;
                        foreach (var key in settings.MouseGestures.Keys)
                        {
                            if (key.Equals(processName, StringComparison.OrdinalIgnoreCase) || 
                                key.Equals(processName + ".exe", StringComparison.OrdinalIgnoreCase))
                            {
                                isTarget = true;
                                break;
                            }
                        }

                        if (isTarget)
                        {
                            _isRightDown = true;
                            _path.Clear();
                            _path.Add(Cursor.Position);
                            return 1; // Block the original right down
                        }
                    }
                    
                    // If not a target process or process name is empty, just let it pass through normally
                    return CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
                }
                else if (msg == WM_MOUSEMOVE && _isRightDown)
                {
                    var pos = Cursor.Position;
                    var last = _path[_path.Count - 1];
                    // Add point if moved slightly
                    if (Math.Abs(pos.X - last.X) > 2 || Math.Abs(pos.Y - last.Y) > 2)
                    {
                        _path.Add(pos);
                    }
                    // Optionally, you could draw gesture trails here
                }
                else if (msg == WM_RBUTTONUP && _isRightDown)
                {
                    _isRightDown = false;
                    _path.Add(Cursor.Position);

                    string vector = CalculateGestureVector(_path);

                    if (string.IsNullOrEmpty(vector))
                    {
                        // It was just a click, not a drag. Pass the click through synthetically.
                        SimulateRightClick(Cursor.Position);
                    }
                    else
                    {
                        // A gesture was made!
                        ExecuteGesture(vector);
                    }
                    return 1; // Block the original right up
                }
            }

            return CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
        }

        private void SimulateRightClick(System.Drawing.Point pos)
        {
            // First, move to the position (optional, but safe)
            Win32.SetCursorPos(pos.X, pos.Y);
            
            // Send synthetic down and up with magic extra info
            Win32.mouse_event(Win32.MOUSEEVENTF_RIGHTDOWN, 0, 0, 0, GESTURE_MAGIC_EXTRA_INFO);
            Win32.mouse_event(Win32.MOUSEEVENTF_RIGHTUP, 0, 0, 0, GESTURE_MAGIC_EXTRA_INFO);
        }

        private string CalculateGestureVector(List<System.Drawing.Point> path)
        {
            if (path.Count < 2) return "";

            var start = path[0];
            var end = path[path.Count - 1];

            // Check if overall distance is large enough
            double distance = Math.Sqrt(Math.Pow(end.X - start.X, 2) + Math.Pow(end.Y - start.Y, 2));
            if (distance < GESTURE_MIN_DISTANCE) return "";

            // For simplicity, we calculate the vectors between segments that move at least min_distance
            var vectorBuilder = new List<string>();
            var currentStart = path[0];

            for (int i = 1; i < path.Count; i++)
            {
                var pt = path[i];
                var dx = pt.X - currentStart.X;
                var dy = pt.Y - currentStart.Y;

                if (Math.Abs(dx) >= GESTURE_MIN_DISTANCE || Math.Abs(dy) >= GESTURE_MIN_DISTANCE)
                {
                    string dir = "";
                    if (Math.Abs(dx) > Math.Abs(dy))
                    {
                        dir = dx > 0 ? "Right" : "Left";
                    }
                    else
                    {
                        dir = dy > 0 ? "Down" : "Up";
                    }

                    if (vectorBuilder.Count == 0 || vectorBuilder[vectorBuilder.Count - 1] != dir)
                    {
                        vectorBuilder.Add(dir);
                    }
                    currentStart = pt;
                }
            }

            return string.Join(",", vectorBuilder);
        }

        private void ExecuteGesture(string vector)
        {
            string processName = GetForegroundProcessName();
            if (string.IsNullOrEmpty(processName)) return;

            var settings = SettingsService.Load();
            
            // Case-insensitive match for process name (e.g., "chrome.exe" or "chrome")
            string targetKey = "";
            foreach (var key in settings.MouseGestures.Keys)
            {
                if (key.Equals(processName, StringComparison.OrdinalIgnoreCase) || 
                    key.Equals(processName + ".exe", StringComparison.OrdinalIgnoreCase))
                {
                    targetKey = key;
                    break;
                }
            }

            if (string.IsNullOrEmpty(targetKey)) return;

            var gestures = settings.MouseGestures[targetKey];
            if (gestures.TryGetValue(vector, out var hotkey) && !string.IsNullOrWhiteSpace(hotkey))
            {
                // Send hotkey with a slightly longer delay to ensure mouse hook processing completes
                // and the target application is ready to receive keyboard input
                System.Threading.Tasks.Task.Run(async () => {
                    await System.Threading.Tasks.Task.Delay(50);
                    HotkeySender.SendDetailed(hotkey);
                });
            }
        }

        private string GetForegroundProcessName()
        {
            nint hwnd = Win32.GetForegroundWindow();
            if (hwnd == nint.Zero) return "";

            Win32.GetWindowThreadProcessId(hwnd, out uint pid);
            if (pid == 0) return "";

            try
            {
                using var process = Process.GetProcessById((int)pid);
                return process.ProcessName; // typically "chrome", "explorer", etc (without .exe)
            }
            catch
            {
                return "";
            }
        }

        public void Dispose()
        {
            Stop();
        }

        // Win32 API
        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern nint SetWindowsHookEx(int idHook, LowLevelMouseProc lpfn, nint hMod, uint dwThreadId);

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool UnhookWindowsHookEx(nint hhk);

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern nint CallNextHookEx(nint hhk, int nCode, nint wParam, nint lParam);

        [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern nint GetModuleHandle(string lpModuleName);

        [StructLayout(LayoutKind.Sequential)]
        private struct POINT
        {
            public int x;
            public int y;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct MSLLHOOKSTRUCT
        {
            public POINT pt;
            public uint mouseData;
            public uint flags;
            public uint time;
            public nint dwExtraInfo;
        }
    }
}
